# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [5]:
import numpy as np
a = np.arange(12).reshape(3,4)
print(a.sum())
print(np.sum(a))
print(sum(a))
print("我們可以看到, sum(a)回傳的是對於矩陣每行的和")
print("\n而a.sum()和np.sum(a)的差異則較難直接看出來, \na.sum()是直接使用a這個np class 裡面的method, \nnp.sum(a)則是把a傳入np.sum這個函式")

66
66
[12 15 18 21]
我們可以看到, sum(a)回傳的是對於矩陣每行的和

而a.sum()和np.sum(a)的差異則較難直接看出來, 
a.sum()是直接使用a這個np class 裡面的method, 
np.sum(a)則是把a傳入np.sum這個函式


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
# 記得先 Import 正確的套件
import numpy as np

In [8]:
A = np.random.random((5, 5))
print(A)
A=(A-A.mean())/(A.std())
print(A)
print(A.mean())
print(A.std())

[[0.39476657 0.26646778 0.14144445 0.66332447 0.74562856]
 [0.82021592 0.948215   0.8003026  0.06559811 0.46783775]
 [0.65851691 0.29009042 0.82147126 0.74324996 0.26066934]
 [0.87858583 0.30296303 0.57252742 0.02892883 0.28556159]
 [0.89625278 0.20807019 0.97885741 0.42287146 0.62404781]]
[[-0.47424077 -0.91936185 -1.35311905  0.45749669  0.74304334]
 [ 1.00181748  1.44589875  0.93273001 -1.61626111 -0.22072686]
 [ 0.44081731 -0.83740523  1.00617276  0.734791   -0.93947902]
 [ 1.20432662 -0.79274488  0.1424845  -1.74348187 -0.85311762]
 [ 1.26562053 -1.12196703  1.55220984 -0.37673338  0.32122986]]
2.597921877622866e-16
1.0000000000000002


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [13]:
A = np.random.random(10)
A[np.argmax(A)]=-1
print(A)

[ 0.760527    0.00120479  0.41432916  0.71537469  0.66436029 -1.
  0.09278166  0.66912377  0.64181636  0.61669776]
